### ISSUE TITLE
Vagrant build is broken

### ISSUE THREAD

**Issue by Akendo** [coddingtonbear/inthe.am#264]
Hi I want to test this software, i saw a Vagrantfile. But running it leads to to some issues. 
Following error message comes during the the vagrant up
```
==> default: bower                                            EPERM EPERM: operation not permitted, chown '/var/www/twweb/bower_components/chardin.js/.bower.json'
==> default: 
==> default: Stack trace:
==> default: /usr/local/lib/node_modules/bower/lib/node_modules/fstream/lib/writer.js:306:21
==> default: /usr/local/lib/node_modules/bower/lib/node_modules/fstream/node_modules/graceful-fs/polyfills.js:210:7
==> default: /usr/local/lib/node_modules/bower/lib/node_modules/bower-json/node_modules/graceful-fs/polyfills.js:133:7
==> default: FSReqWrap.oncomplete (fs.js:82:15)
==> default: 
==> default: Console trace:
==> default: Error
==> default:     at StandardRenderer.error (/usr/local/lib/node_modules/bower/lib/lib/renderers/StandardRenderer.js:83:37)
==> default:     at Logger.<anonymous> (/usr/local/lib/node_modules/bower/lib/bin/bower:113:26)
==> default:     at emitOne (events.js:77:13)
==> default:     at Logger.emit (events.js:169:7)
==> default:     at Logger.emit (/usr/local/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
==> default:     at /usr/local/lib/node_modules/bower/lib/lib/commands/index.js:48:20
==> default:     at _rejected (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
==> default:     at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
==> default:     at Promise.when (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
==> default:     at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
==> default: 
==> default: System info:
==> default: Bower version: 1.7.6
==> default: Node version: 5.0.0
==> default: OS: Linux 3.2.0-23-generic-pae ia32
==> default: + set -e
==> default: + echo 'running ember build'
==> default: running ember build
==> default: + ember build
==> default: Could not start watchman; falling back to NodeWatcher for file system events.
==> default: Visit http://ember-cli.com/user-guide/#watchman for more info.
==> default: Cannot find module '/var/www/twweb/bower_components/ember/ember-template-compiler'
==> default: Error: Cannot find module '/var/www/twweb/bower_components/ember/ember-template-compiler'
==> default:     at Function.Module._resolveFilename (module.js:337:15)
==> default:     at Function.Module._load (module.js:287:25)
==> default:     at Module.require (module.js:366:17)
==> default:     at require (module.js:385:17)
==> default:     at Class.module.exports.included (/var/www/twweb/node_modules/ember-cli-htmlbars-inline-precompile/index.js:17:20)
==> default:     at EmberApp.<anonymous> (/var/www/twweb/node_modules/ember-cli/lib/broccoli/ember-app.js:433:15)
==> default:     at Array.filter (native)
==> default:     at EmberApp._notifyAddonIncluded (/var/www/twweb/node_modules/ember-cli/lib/broccoli/ember-app.js:428:45)
==> default:     at new EmberApp (/var/www/twweb/node_modules/ember-cli/lib/broccoli/ember-app.js:109:8)
==> default:     at module.exports (/var/www/twweb/ember-cli-build.js:4:15)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
```

Any suggestion? 

Best regards

**Comment by coddingtonbear** [comment]
Fixed a little bit earlier today!  You'll probably want to `vagrant destroy` then `vagrant up` again.

Good luck, and sorry for the trouble!
