### ISSUE TITLE
`update_statistics` and `gc_large_repos` overnight tasks are not executing currently.

### ISSUE THREAD

**Issue by coddingtonbear** [coddingtonbear/inthe.am#279]
When investigating a problem this morning, I found this notice in the logs for the above:

```
System check identified some issues:

WARNINGS:
taskmanager.UserMetadata.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
Traceback (most recent call last):
  File "/var/www/twweb/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/var/www/twweb/inthe_am/taskmanager/management/commands/taskstore.py", line 107, in handle
    for store in TaskStore.objects.order_by('-last_synced'):
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/models/query.py", line 162, in __iter__
    self._fetch_all()
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/envs/twweb/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: taskmanager_taskstore.secret_id
```

_Clearly_ it's connecting to sqlite (like it would for a dev environment) for some reason rather than the proper database backend.  This is...a problem.

**Comment by coddingtonbear** [comment]
Fixed this some time ago.
